version: '3.8'

services:
    mosquitto:
        image: eclipse-mosquitto:2
        ports:
            - 1884:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - /home/iot/mosquitto/config:/mosquitto/config
            - /home/iot/mosquitto/data:/mosquitto/data
            - /home/iot/mosquitto/log:/mosquitto/log
        networks:
            - mosquitto
networks:
    mosquitto:
        name: iot
        driver: bridge
